name: CI Build-Tests
on: [push, pull_request]
jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install rapidjson-dev libmapbox-variant-dev libprotozero-dev virtualenv
    - name: Install python dependencies
      run: |
        virtualenv venv
        ./venv/bin/pip install flake8 pytest pybind11 mypy types-psycopg2 types-pyyaml
        ./venv/bin/pip install .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ./venv/bin/flake8 --count --select=E9,F63,F7,F82 --show-source --statistics src
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        ./venv/bin/flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --extend-ignore=E302,E722 --statistics src
    - name: Check typing
      run: ./venv/bin/mypy
    - name: Install PostgreSQL
      run: |
        sudo apt-get install postgresql postgresql-client
        sudo systemctl restart postgresql
        sudo -u postgres createuser -s runner
    - name: Test with pytest
      run: |
        ./venv/bin/pytest tests
