name: CI Build-Tests
on: [push, pull_request]
jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install rapidjson-dev libmapbox-variant-dev libprotozero-dev virtualenv
    - name: Install python dependencies
      run: |
        virtualenv venv
        ./venv/bin/pip install flake8 pytest pybind11 mypy types-psycopg2 types-pyyaml
        ./venv/bin/pip install .
    - name: Lint with flake8
      run: |
        ./venv/bin/flake8 src tests
    - name: Check typing
      run: ./venv/bin/mypy
    - name: Install PostgreSQL
      run: |
        sudo apt-get install postgresql postgresql-client
        sudo systemctl restart postgresql
        sudo -u postgres createuser -s runner
    - name: Test with pytest
      run: |
        ./venv/bin/pytest tests
